// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vapos2.Context;

namespace Vapos2.Migrations
{
    [DbContext(typeof(RegistrosContext))]
    partial class RegistrosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vapos2.Models.Persona", b =>
                {
                    b.Property<string>("nombreApe")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("telefono");

                    b.HasKey("nombreApe");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Vapos2.Models.Registro", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Detalles");

                    b.Property<string>("IdVapo");

                    b.Property<bool>("Prueba_Estanqueidad");

                    b.Property<bool>("Prueba_Funcionamiento");

                    b.Property<bool>("Prueba_Hidráulica");

                    b.Property<DateTime>("fecha");

                    b.Property<string>("nombreApe");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdVapo");

                    b.HasIndex("nombreApe");

                    b.ToTable("Registos");
                });

            modelBuilder.Entity("Vapos2.Models.Vapo", b =>
                {
                    b.Property<string>("IdVapo")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Intecambiador_Der");

                    b.Property<int>("Intecambiador_Izq");

                    b.HasKey("IdVapo");

                    b.ToTable("Vapos");
                });

            modelBuilder.Entity("Vapos2.Models.Registro", b =>
                {
                    b.HasOne("Vapos2.Models.Vapo", "vaporizator")
                        .WithMany()
                        .HasForeignKey("IdVapo");

                    b.HasOne("Vapos2.Models.Persona", "responsable")
                        .WithMany()
                        .HasForeignKey("nombreApe");
                });
#pragma warning restore 612, 618
        }
    }
}
